# Uncomment the next line to define a global platform for your project
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '9.0'
use_frameworks!

target 'LivingBIM' do

  # Pods for LivingBIM
  # pod 'box-ios-sdk', :git => 'git@github.com:box/box-ios-sdk.git'
  pod 'box-ios-sdk'
  pod 'Alamofire', '~> 4.0'
  pod 'Kanna', '~> 2.0.0'
  pod 'SwiftyJSON'
  
end
